### PR TITLE
Update to 4.1.1

### LINKED ISSUE #5: Additional animation triggers
Now we load, by default, on the scroll. We can have an option to animate on load and on hover as well.

### LINKED ISSUE #79: Improve animation picker
Given it has a lot of values, users have complained about the easy of use. Here are few ways to improve it:

- [x] Add search
- [x] Maybe display most used animations on top, added in browser storage
- [x] Categorize the animations

We can use some or all the ways to improve.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
I have updated the file with the new version and put the new animations in the `data.js`.**But they are not working and I can not understand the code.**

@HardeepAsrani could please put some comments on the code?. I want every single action comment  - especially in the one that you use the `replace function`.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel They're not working because if you see both CSS files (older and newer version), you will notice both of them have very different classes that they use. You will have to use search/replace to make bring new CSS class structure to inline with older one.

Also, the current version that we use it `3.7.0` so make sure to compare our .min.css file with the original 3.7.0 file to make sure we didn't make any changes to the original file. (I remember making some changes but it's been years so it's better to make sure).

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I have updated up to the new version **, and I have rewritten most of the code**  ( there is still work to do ). 
The original code used many bad practices and workarounds, making it hard to read it (and some hidden bugs). 

Also made a translation function for the frontend to rename the old values to the new ones. What is a good method to resolve it on the backend for transforming the old value into the new ones?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, it was being worked by Maria on Select Component but was left in between so feel free to rewrite the Select Component, I don't like the code much either.

**Comment by HardeepAsrani** [comment]
This https://github.com/Codeinwp/gutenberg-animation/issues/79

**Pull request closed without merging**
